#!/bin/sh
# fzf based file manager. recursive, cd, trash, git log file, git log . 
FIND="find ${1:-.} -not -path '*/.git*'" 
$FIND | fzf -e --preview='bat --color=always {}' --preview-window=':80%' \
    --bind="ctrl-x:execute(rm {})+reload(find ${1:-.} -not -path '*/.git*')" \
    --header 'X:rm'

