# Generated from /home/dh/repo/helix/runtime/themes/dracula.toml
# Converted by hx2kak.py

# Palette
declare-option str background "rgb:282a36"
declare-option str black "rgb:191a21"
declare-option str comment "rgb:6272a4"
declare-option str current_line "rgb:44475a"
declare-option str cursorline "rgb:2d303e"
declare-option str cyan "rgb:8be9fd"
declare-option str darker "rgb:222430"
declare-option str foreground "rgb:f8f8f2"
declare-option str green "rgb:50fa7b"
declare-option str grey "rgb:666771"
declare-option str indent "rgb:56596a"
declare-option str orange "rgb:ffb86c"
declare-option str pink "rgb:ff79c6"
declare-option str purple "rgb:bd93f9"
declare-option str red "rgb:ff5555"
declare-option str selection "rgb:363848"
declare-option str whitespace "rgb:586693"
declare-option str yellow "rgb:f1fa8c"

# UI
set-face global Default rgb:f8f8f2,rgb:282a36
set-face global PrimaryCursor rgb:282a36,rgb:bd93f9+d
set-face global ui_cursor_insert rgb:282a36,rgb:50fa7b+d
set-face global MatchingChar rgb:f8f8f2,rgb:666771
set-face global ui_cursor_normal rgb:282a36,rgb:bd93f9+d
set-face global ui_cursor_primary_insert rgb:282a36,rgb:50fa7b
set-face global ui_cursor_primary_normal rgb:282a36,rgb:bd93f9
set-face global ui_cursor_primary_select rgb:282a36,rgb:8be9fd
set-face global ui_cursor_select rgb:282a36,rgb:8be9fd+d
set-face global LineHighlight ,rgb:2d303e
set-face global ui_debug rgb:ff5555
set-face global InfoBlock rgb:f8f8f2,rgb:191a21
set-face global ui_highlight_frameline rgb:282a36,rgb:ff5555
set-face global LineNumbers rgb:6272a4
set-face global LineNumberCursor rgb:f8f8f2
set-face global MenuForeground rgb:f8f8f2,rgb:44475a
set-face global ui_menu_scroll rgb:f8f8f2,rgb:44475a
set-face global MenuBackground rgb:44475a,rgb:bd93f9+d
set-face global Information rgb:f8f8f2,rgb:191a21
set-face global PrimarySelection ,rgb:363848
set-face global ui_selection_primary ,rgb:44475a
set-face global StatusLine rgb:f8f8f2,rgb:222430
set-face global StatusLineInfo rgb:6272a4,rgb:222430
set-face global StatusLineModeInsert rgb:191a21,rgb:50fa7b+b
set-face global StatusLineModeNormal rgb:191a21,rgb:bd93f9+b
set-face global StatusLineModeSelect rgb:191a21,rgb:8be9fd+b
set-face global DefaultText rgb:f8f8f2
set-face global DefaultFocus rgb:8be9fd
set-face global ui_text_directory rgb:8be9fd
set-face global ui_virtual_indent_guide rgb:56596a
set-face global ui_virtual_inlay_hint rgb:8be9fd
set-face global ui_virtual_inlay_hint_parameter rgb:8be9fd+i+d
set-face global ui_virtual_inlay_hint_type rgb:8be9fd+i+d
set-face global ui_virtual_jump_label rgb:ff79c6+b
set-face global ColumnRuler ,rgb:191a21
set-face global Whitespace rgb:586693
set-face global ui_virtual_wrap rgb:44475a
set-face global BufferPadding rgb:f8f8f2

# Diagnostics
set-face global ts_diagnostic rgb:ffb86c+u
set-face global DiagnosticHint rgb:bd93f9+u
set-face global DiagnosticWarning rgb:f1fa8c+u
set-face global DiagnosticError rgb:ff5555+u
set-face global DiagnosticInfo rgb:8be9fd+u
set-face global ts_comment_unused +d
set-face global ts_markup_strikethrough +s
set-face global ts_error rgb:ff5555
set-face global ts_hint rgb:bd93f9
set-face global ts_info rgb:8be9fd
set-face global ts_warning rgb:f1fa8c

# Tree-sitter
set-face global ts_annotation rgb:f8f8f2
set-face global ts_attribute rgb:50fa7b+i
set-face global ts_comment rgb:6272a4
set-face global ts_comment_block rgb:6272a4
set-face global ts_comment_block_documentation rgb:6272a4
set-face global ts_comment_line rgb:6272a4
set-face global ts_comment_line_documentation rgb:6272a4
set-face global ts_constant rgb:bd93f9
set-face global ts_constant_builtin rgb:bd93f9
set-face global ts_constant_builtin_boolean rgb:bd93f9
set-face global ts_constant_character rgb:8be9fd
set-face global ts_constant_character_escape rgb:ff79c6
set-face global ts_constant_macro rgb:bd93f9
set-face global ts_constant_numeric rgb:bd93f9
set-face global ts_constructor rgb:bd93f9
set-face global ts_definition rgb:8be9fd+u
set-face global ts_diff_delta rgb:ffb86c
set-face global ts_diff_minus rgb:ff5555
set-face global ts_diff_plus rgb:50fa7b
set-face global ts_function rgb:50fa7b
set-face global ts_function_builtin rgb:50fa7b
set-face global ts_function_call rgb:50fa7b
set-face global ts_function_macro rgb:bd93f9
set-face global ts_function_method rgb:50fa7b
set-face global ts_keyword rgb:ff79c6
set-face global ts_keyword_control_conditional rgb:ff79c6
set-face global ts_keyword_control_exception rgb:bd93f9
set-face global ts_keyword_control_import rgb:ff79c6
set-face global ts_keyword_control_repeat rgb:ff79c6
set-face global ts_keyword_directive rgb:50fa7b
set-face global ts_keyword_function rgb:ff79c6
set-face global ts_keyword_operator rgb:ff79c6
set-face global ts_keyword_return rgb:ff79c6
set-face global ts_keyword_storage rgb:ff79c6
set-face global ts_keyword_storage_modifier rgb:ff79c6
set-face global ts_keyword_storage_type rgb:8be9fd+i
set-face global ts_label rgb:8be9fd
set-face global ts_markup_bold rgb:ffb86c+b
set-face global ts_markup_heading rgb:bd93f9+b
set-face global ts_markup_italic rgb:f1fa8c+i
set-face global ts_markup_link_text rgb:ff79c6
set-face global ts_markup_link_url rgb:8be9fd
set-face global ts_markup_list rgb:8be9fd
set-face global ts_markup_quote rgb:f1fa8c+i
set-face global ts_markup_raw rgb:f8f8f2
set-face global ts_punctuation rgb:f8f8f2
set-face global ts_punctuation_bracket rgb:f8f8f2
set-face global ts_punctuation_delimiter rgb:f8f8f2
set-face global ts_punctuation_special rgb:ff79c6
set-face global ts_special rgb:ff79c6
set-face global ts_string rgb:f1fa8c
set-face global ts_string_regexp rgb:ff5555
set-face global ts_string_special rgb:ffb86c
set-face global ts_string_symbol rgb:f1fa8c
set-face global ts_tag rgb:ff79c6
set-face global ts_tag_attribute rgb:bd93f9
set-face global ts_tag_delimiter rgb:f8f8f2
set-face global ts_type rgb:8be9fd+i
set-face global ts_type_builtin rgb:8be9fd
set-face global ts_type_enum_variant rgb:f8f8f2+i
set-face global ts_variable rgb:f8f8f2
set-face global ts_variable_builtin rgb:bd93f9+i
set-face global ts_variable_other rgb:f8f8f2
set-face global ts_variable_other_member rgb:f8f8f2
set-face global ts_variable_parameter rgb:ffb86c+i
