# Generated from /home/dh/repo/helix/runtime/themes/hex_toxic.toml
# Converted by hx2kak.py

# Palette
declare-option str t1 "rgb:101719"
declare-option str t2 "rgb:1b2a32"
declare-option str t3 "rgb:4b5968"
declare-option str t4 "rgb:8792ab"
declare-option str t5 "rgb:6f91bc"
declare-option str t6 "rgb:8bb2b9"
declare-option str t7 "rgb:eeac90"
declare-option str t8 "rgb:b0bd9f"
declare-option str t9 "rgb:b3ccd0"
declare-option str t10 "rgb:b0d4d8"
declare-option str t11 "rgb:ffbf52"
declare-option str highlight "rgb:ff0a50"
declare-option str highlight_two "rgb:0affa9"
declare-option str highlight_three "rgb:f8ed8b"
declare-option str selection "rgb:b10656"
declare-option str selection_fg "rgb:101719"
declare-option str black "rgb:000000"
declare-option str comment "rgb:417e8c"
declare-option str comment_doc "rgb:234048"
declare-option str hints "rgb:39515c"
declare-option str ruler "rgb:1e3039"
declare-option str error "rgb:ff0900"
declare-option str warning "rgb:ffbf00"
declare-option str display "rgb:57ff89"
declare-option str info "rgb:dad7d5"
declare-option str diff_minus "rgb:ff4000"
declare-option str diff_delta "rgb:0078bd"
declare-option str diff_plus "rgb:c9d400"
declare-option str diff_delta_moved "rgb:0048bd"

# UI
set-face global ui_cursor_primary_insert rgb:1b2a32,rgb:ff0a50
set-face global ui_cursor_primary_select rgb:1b2a32,rgb:0affa9
set-face global SecondaryCursor rgb:101719,rgb:f8ed8b
set-face global MatchingChar rgb:ff0a50,rgb:101719+b
set-face global LineHighlight ,rgb:1e3039
set-face global ui_cursorline_secondary ,rgb:1e3039
set-face global LineNumbers rgb:4b5968,rgb:1b2a32
set-face global LineNumberCursor rgb:f8ed8b,rgb:1b2a32
set-face global Gutter ,rgb:1b2a32
set-face global Default rgb:8792ab,rgb:1b2a32
set-face global ui_background_separator rgb:4b5968
set-face global InfoBlock rgb:8792ab,rgb:101719
set-face global MenuForeground rgb:8792ab,rgb:101719
set-face global MenuBackground rgb:f8ed8b,rgb:101719
set-face global Information rgb:8792ab,rgb:101719
set-face global BufferPadding rgb:8792ab
set-face global PrimarySelection rgb:101719,rgb:b10656
set-face global StatusLine rgb:8792ab,rgb:101719
set-face global StatusLineInfo rgb:8792ab,rgb:101719
set-face global StatusLineModeNormal rgb:4b5968,rgb:101719
set-face global StatusLineModeInsert rgb:4b5968,rgb:101719
set-face global StatusLineModeSelect rgb:ff0a50,rgb:8792ab
set-face global DefaultText rgb:8792ab
set-face global DefaultFocus rgb:f8ed8b+b
set-face global ColumnRuler ,rgb:1e3039
set-face global ui_virtual_indent_guide rgb:4b5968
set-face global Whitespace rgb:4b5968
set-face global ui_virtual_jump_label rgb:ffbf52+b
set-face global ui_virtual_inlay_hint rgb:39515c+b
set-face global ui_bufferline rgb:4b5968,rgb:101719
set-face global ui_bufferline_active rgb:eeac90,rgb:1b2a32

# Diagnostics
set-face global DiagnosticError rgb:ff0900+u
set-face global DiagnosticWarning rgb:ffbf00+u
set-face global DiagnosticInfo rgb:dad7d5+u
set-face global DiagnosticHint rgb:57ff89+u
set-face global ts_error rgb:ff0900+b
set-face global ts_warning rgb:ffbf00+b
set-face global ts_info rgb:dad7d5+b
set-face global ts_hint rgb:57ff89+b

# Tree-sitter
set-face global ts_comment rgb:417e8c
set-face global ts_comment_block_documentation ,rgb:234048+i
set-face global ts_comment_line_documentation ,rgb:234048+i
set-face global ts_constant rgb:ffbf52
set-face global ts_function rgb:b0d4d8
set-face global ts_function_method rgb:eeac90
set-face global ts_function_macro rgb:eeac90
set-face global ts_keyword_storage_modifier rgb:eeac90
set-face global ts_keyword_control_import rgb:b0bd9f
set-face global ts_keyword_control rgb:b0bd9f
set-face global ts_keyword_function rgb:ffbf52
set-face global ts_keyword rgb:8bb2b9
set-face global ts_operator rgb:b0bd9f
set-face global ts_punctuation rgb:b3ccd0
set-face global ts_string rgb:8bb2b9+i
set-face global ts_string_regexp rgb:8bb2b9
set-face global ts_tag rgb:8792ab
set-face global ts_type rgb:b0bd9f+b
set-face global ts_namespace rgb:8bb2b9+b
set-face global ts_variable rgb:8792ab
set-face global ts_variable_parameter rgb:8bb2b9
set-face global ts_variable_other_member rgb:4b5968
set-face global ts_label rgb:8792ab
set-face global ts_diff_plus rgb:c9d400
set-face global ts_diff_delta rgb:0078bd
set-face global ts_diff_delta_moved rgb:0048bd
set-face global ts_diff_minus rgb:ff4000
set-face global ts_special rgb:eeac90+b
set-face global ts_markup_heading rgb:eeac90
set-face global ts_markup_list rgb:eeac90
set-face global ts_markup_bold rgb:8792ab
set-face global ts_markup_italic rgb:8792ab
set-face global ts_markup_strikethrough rgb:8792ab+s
set-face global ts_markup_link_url rgb:ffbf52+u
set-face global ts_markup_link_text rgb:ffbf52
set-face global ts_markup_quote rgb:6f91bc
set-face global ts_markup_raw rgb:8792ab
